version: "3.4"

services:
    postgres:
        restart: always
        image: postgres:16.2
        container_name: ${POSTGRES_HOST}
        command: -p ${POSTGRES_PORT}
        ports:
            - "127.0.0.1:8503:${POSTGRES_PORT}"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - /containers/alch/postgres_data:/var/lib/postgresql/data
        networks:
            - default

    service:
        restart: always
        build:
            context: .
            target: python
        container_name: ${SERVICE_NAME}
        command: bash -c "gunicorn main:app -w 4 -k uvicorn.workers.UvicornH11Worker  -b 0.0.0.0:${SERVICE_PORT}"
        env_file:
            - .env
        volumes:
            - /containers/alch/${SERVICE_NAME}/logs:/app/logs
            - ./static:/static
        links:
            - postgres
            - migration
            - cache
        depends_on:
            - postgres
            - migration
            - cache
        ports:
            - "127.0.0.1:${SERVICE_PORT}:${SERVICE_PORT}"
        networks:
            - default

    pgAdmin:
        restart: always
        image: hub.xdev.team/dpage/pgadmin4:6.15
        container_name: alch_pgadmin
        links:
            - postgres:postgres
        ports:
            - "127.0.0.1:${PGADMIN_PORT}:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        depends_on:
            - postgres
        networks:
            - default

    migration:
        build:
            context: .
            target: migration
        links:
            - postgres
        depends_on:
            - postgres
        env_file:
            - .env
        networks:
            - default

    cache:
        image: redis:6.2.7-alpine
        restart: always
        command: redis-server  --loglevel warning --requirepass ${REDIS_PASSWORD}


networks:
    default:
        external:
            name: alch_backend
